config/routes.rb
Rails.application.routes.draw do
  
  get 'main/index'

  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users
  resources :word_categories
  resources :words
  resources :dictionaries
  resources :word_types
  resources :languages
  resources :categories

  root 'main#index', as: 'main'
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/models/word_category.rb
class WordCategory < ActiveRecord::Base
    self.primary_keys = :idWord,:idCategory
end

app/models/word_type.rb
class WordType < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_words = Word.count
  end
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
      params.require(:dictionary).permit(:IDDictionary, :IDUSer, :Name, :IDSourceLanguage, :IDDestinationLanguage)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    skip_before_action :authorize
  def index
  @categories = Category.all
  @word_types = WordType.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created."  }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated."  }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words, @alphaParams = (Word.select{|it| it.IDUser == session[:user_id]}).alpha_paginate(params[:letter], {:bootstrap3 => true, :pagination_class => "pagination"}) {|it| it.Word}
    end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to words_url, notice: 'Word was successfully created.' }
        format.json { render :index, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to words_url, notice: 'Word was successfully updated.' }
        format.json { render :index, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:Word, :Translation, :IDWordType, :IPA, :IDDictionary, :IDUser)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      @current_user ||= User.find_by_id(session[:user_id])
    end

     def logged_in?
       current_user != nil
     end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/word_categories_helper.rb
module WordCategoriesHelper
end

app/helpers/word_types_helper.rb
module WordTypesHelper
end

app/helpers/words_helper.rb
module WordsHelper

end

app/views/dictionaries/_form.html.erb
<%= form_for(@dictionary) do |f| %>
  <% if @dictionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</h2>

      <ul>
      <% @dictionary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :IDDictionary %><br>
    <%= f.number_field :IDDictionary %>
  </div>
  <div class="field">
    <%= f.label :IDUSer %><br>
    <%= f.number_field :IDUSer %>
  </div>
  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :IDSourceLanguage %><br>
    <%= f.number_field :IDSourceLanguage %>
  </div>
  <div class="field">
    <%= f.label :IDDestinationLanguage %><br>
    <%= f.number_field :IDDestinationLanguage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dictionaries/edit.html.erb
<h1>Editing Dictionary</h1>

<%= render 'form' %>

<%= link_to 'Show', @dictionary %> |
<%= link_to 'Back', dictionaries_path %>

app/views/dictionaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dictionaries</h1>

<table  class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Iddictionary</th>
      <th>Iduser</th>
      <th>Name</th>
      <th>Idsourcelanguage</th>
      <th>Iddestinationlanguage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dictionaries.each do |dictionary| %>
      <tr>
        <td><%= dictionary.IDDictionary %></td>
        <td><%= dictionary.IDUSer %></td>
        <td><%= dictionary.Name %></td>
        <td><%= dictionary.IDSourceLanguage %></td>
        <td><%= dictionary.IDDestinationLanguage %></td>
        <td><%= link_to 'Show', dictionary %></td>
        <td><%= link_to 'Edit', edit_dictionary_path(dictionary) %></td>
        <td><%= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dictionary', new_dictionary_path %>

app/views/dictionaries/new.html.erb
<h1>New Dictionary</h1>

<%= render 'form' %>

<%= link_to 'Back', dictionaries_path %>

app/views/dictionaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Iddictionary:</strong>
  <%= @dictionary.IDDictionary %>
</p>

<p>
  <strong>Iduser:</strong>
  <%= @dictionary.IDUSer %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dictionary.Name %>
</p>

<p>
  <strong>Idsourcelanguage:</strong>
  <%= @dictionary.IDSourceLanguage %>
</p>

<p>
  <strong>Iddestinationlanguage:</strong>
  <%= @dictionary.IDDestinationLanguage %>
</p>

<%= link_to 'Edit', edit_dictionary_path(@dictionary) %> |
<%= link_to 'Back', dictionaries_path %>