config/routes.rb
Rails.application.routes.draw do
  
  get 'main/index'

  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users
  resources :word_categories
  resources :words
  resources :dictionaries
  resources :word_types
  resources :languages
  resources :categories

  root 'main#index', as: 'main'
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/models/word_category.rb
class WordCategory < ActiveRecord::Base
    self.primary_keys = :idWord,:idCategory
end

app/models/word_type.rb
class WordType < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_words = Word.count
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:ISOCode, :Description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    skip_before_action :authorize
  def index
  @categories = Category.all
  @word_types = WordType.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      if user[:isAdmin] == true
      redirect_to admin_url
      else 
        redirect_to controller: 'words', action: 'index'
      end
    else
      redirect_to login_url, alert: "Invalid user/password combination"
  end
  end

  def destroy
    session[:user_id] = nil
    redirect_to main_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created."  }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated."  }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words, @alphaParams = (Word.select{|it| it.IDUser == session[:user_id]}).alpha_paginate(params[:letter], {:bootstrap3 => true, :pagination_class => "pagination"}) {|it| it.Word}
    end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to words_url, notice: 'Word was successfully created.' }
        format.json { render :index, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to words_url, notice: 'Word was successfully updated.' }
        format.json { render :index, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:Word, :Translation, :IDWordType, :IPA, :IDDictionary, :IDUser)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      @current_user ||= User.find_by_id(session[:user_id])
    end

     def logged_in?
       current_user != nil
     end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/word_categories_helper.rb
module WordCategoriesHelper
end

app/helpers/word_types_helper.rb
module WordTypesHelper
end

app/helpers/words_helper.rb
module WordsHelper

end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Word %><br>
    <%= f.text_field :Word %>
  </div>
  <div class="field">
    <%= f.label :Translation %><br>
    <%= f.text_field :Translation %>
  </div>
  <div class="field">
    <%= f.label :IDWordType %><br>
    <%= f.collection_select :IDWordType, WordType.order(:Name),:id,:Name, include_blank: true %>
    <%-#= f.number_field :IDWordType -%> 
  </div>
  <div class="field">
    <%= f.label :IPA %><br>
    <%= f.text_field :IPA %>
  </div>
  <div class="field">
    <%= f.hidden_field :IDDictionary, value: 1 %><br>
    </div>
  <div class="field">
    <%= f.hidden_field :IDUser, value: session[:user_id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>
<div>
<%= link_to 'Add Word', new_word_path, {:class => "btn btn-primary"} %>
<br/>
<%= alphabetical_paginate @alphaParams %>
</div>
<br/>
<div id="pagination_table" class="panel panel-default ">
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Word</th>
      <th>Translation</th>
      <th>Word Type</th>
      <th>Ipa</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= link_to word.Word, edit_word_path(word) %></td>
        <td><%= word.Translation %></td>
        <td><%= WordType.find(word.IDWordType).Name %></td>        
        <td><%= word.IPA %></td>
        <td><%= link_to image_tag('trashcan.png'), word, method: :delete, data: { confirm: 'Are you sure?' } %> </td>       
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<%= alphabetical_paginate @alphaParams %>
<br />
<%= link_to 'Add Word', new_word_path, {:class => "btn btn-primary"} %>
</div>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.Word %>
</p>

<p>
  <strong>Translation:</strong>
  <%= @word.Translation %>
</p>

<p>
  <strong>Idwordtype:</strong>
  <%= @word.IDWordType %>
</p>

<p>
  <strong>Ipa:</strong>
  <%= @word.IPA %>
</p>

<p>
  <strong>Iddictionary:</strong>
  <%= @word.IDDictionary %>
</p>

<p>
  <strong>Iduser:</strong>
  <%= @word.IDUser %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>